version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
        #執行AWS認證
      - $(aws ecr get-login --no-include-email --registry-ids 204065533127  --region ap-northeast-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - sh build.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
        #從ECR中最新版本的Dockerfile
      - docker push 204065533127.dkr.ecr.ap-northeast-1.amazonaws.com/project01-repo:latest
